helloworld/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_post_list, name='home'),
    path('<int:post_id>/', views.blog_post_details, name='blog_post_details'),
]

helloworld/helloworld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('blog/', include('blog.urls'))
]

helloworld/pages/urls.py
from django.urls import path
from .views import home, page1, page2

app_name = 'pages'
urlpatterns = [
    path('', home, name='home'),
    path('page1', page1, name='page1'),
    path('page2', page2, name='page2'),
]

helloworld/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Default title {% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
  </head>
  <body>
    {% block navigation %}
    <nav>
      <div class="nav-wrapper">
        <a href="{% url 'pages:home'%}" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="{% url 'pages:home'%}">Home</a></li>
          <li><a href="{% url 'blog:home' %}">Blog Post</a></li>
        </ul>
      </div>
    </nav>
    {# end block navigation #}
    {% endblock %} 
    {% block 'content' %} {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

helloworld/templates/blog_post.html
{% extends 'base.html' %} 

{% block 'content' %}


<h2>Latest posts</h2> <h5>{{latest_posts|length}} new post{{ latest_posts|length|pluralize }}</h5>
<div class="row">
  {% for new_post in latest_posts %}
    {% include "post_card.html" with post=new_post %}
  {% endfor %}
</div>

<h2>Oldest posts</h2> <h5>{{oldest_posts|length}} new post{{ oldest_posts|length|pluralize }}</h5>
<div class="row">
    {% for old_post in oldest_posts %}
        {% include "post_card.html" with post=old_post %}
    {% endfor %} 
</div>

{% endblock %}

helloworld/templates/blog_post_details.html
{% extends 'base.html' %} {% block 'content' %}

<div class="container">
  <h1>{{ post.title }}</h1>
  <div
    style="
      height: 400px; 
      width:100%; 
      background-image: url({{post.img_url}}); 
      background-position: center; 
      background-repeat: no-repeat;
      background-size: cover;"
  ></div>
  <h5>
    Author: {{ post.author_name }} ( {{post.created_date|date:'d m Y P'}} )
  </h5>
  <p>{{post.body}}</p>
  <br>
  <h4>Comments</h4>
  {% for comment in post.comments %} 
    {% include "comment.html" with comment=comment %} 
  {% endfor %}
</div>

{% endblock %}

helloworld/templates/comment.html
<h5>
    {{ comment.author_name }} ( {{comment.created_date|date:'d m Y P'}} )
</h5>
<p>
    {{ comment.content }}
</p>
<hr>

helloworld/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block 'content' %}
    {# Comment django #}
    {% include 'username.html' %}
    <ol>
    {% for item in breakfast%}
    <li>{{item}}</li>
    {%endfor%}
    </ol>
{% endblock %}

helloworld/templates/page1.html
{% extends 'base.html' %}

{% block title %}
    Page 1 title
{% endblock %}

{% block navigation %}
    No navigation for page1...
{% endblock  %}

helloworld/templates/page2.html
{% extends 'base.html' %}

helloworld/templates/post_card.html
<div class="col s12 m4">
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <a href="{% url 'blog:blog_post_details' post.id %}">
        <img class="activator" src="{{ post.img_url }}" style="height: 350px" />
      </a>
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">
        <a href="{% url 'blog:blog_post_details' post.id %}"> {{post.title}}</a>
        <div class="right">{{post.created_date|date:'d m Y P'}}</div>
      </span>
      <p>
        <a href="{% url 'blog:blog_post_details' post.id %}">View post</a>
      </p>
    </div>
  </div>
</div>

helloworld/templates/username.html
<h1>Hello, {{username|upper}}</h1>